sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - g++-4.8
      - libasound2-dev
    sources:
      - ubuntu-toolchain-r-test
env:
  - CXX=g++-4.8
install:
  - npm install -g npm
  - npm install -g node-gyp
  - npm install
script:
  - node -v
  - npm -v
  - node-gyp rebuild
matrix:
  fast_finish: true
