sudo: false
language: node_js
node_js:
  - 'node'
  - '6'
  - '5'
  - '4'
addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - g++-4.8
      - libasound2-dev
    sources:
      - ubuntu-toolchain-r-test
env:
  - CXX=g++-4.8
install:
  - npm install -g npm
  - npm install -g node-pre-gyp
  - npm install
  - node-pre-gyp clean
  - node-pre-gyp rebuild --mpg123-module=dummy
script:
  - node -v
  - npm -v
  - npm run test
matrix:
  fast_finish: true
